# Generated by Django 4.2.7 on 2023-11-06 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_date',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sku',
            field=models.CharField(default='000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='No name', max_length=200),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='description',
            field=models.CharField(default='No description', max_length=200),
        ),
    ]
